name: Build minieap Windows x86_64
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-libpcap

      - name: Compile minieap inside MSYS2
        shell: msys2 {0}
        run: |
          # 修改config.mk
          sed -i 's/^MODULE_if_impl_sockraw := 1/MODULE_if_impl_sockraw := 0/' config.mk
          sed -i 's/^MODULE_if_impl_libpcap := 0/MODULE_if_impl_libpcap := 1/' config.mk
          sed -i 's/^MODULE_packet_plugin_rjv3 := 0/MODULE_packet_plugin_rjv3 := 1/' config.mk
          sed -i 's/^ENABLE_ICONV := 1/ENABLE_ICONV := 0/' config.mk

          make EXE=minieap.exe

      - name: Copy required dll
        shell: msys2 {0}
        run: |
          cp /mingw64/bin/libwinpthread-1.dll .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: minieap-win-x64
          path: |
            minieap.exe
            libwinpthread-1.dll
