name: Build minieap Windows x86_64
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List source files
        run: |
          pwd
          ls -la
          cat config.mk

      - name: Install build tools
        run: |
          sudo apt update
          sudo apt install -y mingw-w64 gcc-mingw-w64-x86-64 make wget unzip

      # 下载mingw版libpcap
      - name: Get libpcap-mingw for cross compile
        run: |
          wget https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
          unzip WpdPack_4_1_2.zip -d wpdpack

      - name: Cross compile minieap for Windows
        run: |
          # Windows: 关闭sockraw，开启libpcap；开启rjv3；【关键：关闭ICONV】
          sed -i 's/^MODULE_if_impl_sockraw := 1/MODULE_if_impl_sockraw := 0/' config.mk
          sed -i 's/^MODULE_if_impl_libpcap := 0/MODULE_if_impl_libpcap := 1/' config.mk
          sed -i 's/^MODULE_packet_plugin_rjv3 := 0/MODULE_packet_plugin_rjv3 := 1/' config.mk
          sed -i 's/^ENABLE_ICONV := 1/ENABLE_ICONV := 0/' config.mk

          make \
            CC=x86_64-w64-mingw32-gcc \
            EXE=minieap.exe \
            CFLAGS="-I${PWD}/wpdpack/Include" \
            LDFLAGS="-L${PWD}/wpdpack/Lib/x64" \
            LIBS="-lwpcap -lws2_32"

      - name: Upload exe
        uses: actions/upload-artifact@v4
        with:
          name: minieap-win-x64
          path: minieap.exe
